import type { Entitlement } from '../../types/portalTypes';

export const MOCK_ENTITLEMENTS: Entitlement[] = [
  {
    id: 'ent-1',
    productSlug: 'esims',
    productName: 'eSIMs',
    productIcon: 'Smartphone',
    description: 'International mobile connectivity',
    environment: 'test',
    allocation: 1000,
    used: 347,
    remaining: 653,
    cap: 1000,
    status: 'active',
    alertThresholds: {
      enabled: true,
      thresholds: [50, 80, 90, 100],
      recipients: ['admin@example.com'],
    },
    lastAlertedThreshold: null,
    createdAt: '2026-01-15',
    updatedAt: '2026-03-17',
  },
  {
    id: 'ent-2',
    productSlug: 'airport-lounge',
    productName: 'Airport Lounge',
    productIcon: 'Sofa',
    description: 'Premium airport lounge access',
    environment: 'test',
    allocation: 20000,
    used: 17450,
    remaining: 2550,
    cap: 20000,
    status: 'active',
    alertThresholds: {
      enabled: true,
      thresholds: [50, 80, 90, 100],
      recipients: ['admin@example.com'],
    },
    lastAlertedThreshold: 80,
    createdAt: '2026-01-15',
    updatedAt: '2026-03-17',
  },
  {
    id: 'ent-3',
    productSlug: 'airport-transfer',
    productName: 'Airport Transfer',
    productIcon: 'Car',
    description: 'Ground transportation services',
    environment: 'production',
    allocation: 5000,
    used: 1230,
    remaining: 3770,
    cap: 5000,
    status: 'active',
    alertThresholds: {
      enabled: true,
      thresholds: [50, 80, 90, 100],
      recipients: ['admin@example.com'],
    },
    lastAlertedThreshold: null,
    createdAt: '2026-01-15',
    updatedAt: '2026-03-17',
  },
  {
    id: 'ent-4',
    productSlug: 'airport-lounge',
    productName: 'Airport Lounge',
    productIcon: 'Sofa',
    description: 'Premium airport lounge access',
    environment: 'production',
    allocation: 15000,
    used: 13200,
    remaining: 1800,
    cap: 15000,
    status: 'active',
    alertThresholds: {
      enabled: true,
      thresholds: [50, 80, 90, 100],
      recipients: ['admin@example.com'],
    },
    lastAlertedThreshold: 80,
    createdAt: '2026-01-15',
    updatedAt: '2026-03-20',
  },
  {
    id: 'ent-5',
    productSlug: 'fast-track',
    productName: 'Airport Fast Track',
    productIcon: 'Zap',
    description: 'Priority security and immigration lanes',
    environment: 'production',
    allocation: 8000,
    used: 8000,
    remaining: 0,
    cap: 8000,
    status: 'exhausted',
    alertThresholds: {
      enabled: true,
      thresholds: [50, 80, 90, 100],
      recipients: ['admin@example.com'],
    },
    lastAlertedThreshold: 100,
    createdAt: '2026-01-15',
    updatedAt: '2026-03-22',
  },
  {
    id: 'ent-6',
    productSlug: 'esims',
    productName: 'eSIMs',
    productIcon: 'Smartphone',
    description: 'International mobile connectivity',
    environment: 'production',
    allocation: 2000,
    used: 480,
    remaining: 1520,
    cap: 2000,
    status: 'active',
    alertThresholds: {
      enabled: false,
      thresholds: [],
      recipients: [],
    },
    lastAlertedThreshold: null,
    createdAt: '2026-02-01',
    updatedAt: '2026-03-18',
  },
  {
    id: 'ent-7',
    productSlug: 'health-wellness',
    productName: 'Health & Wellness',
    productIcon: 'Heart',
    description: 'Wellness and medical services',
    environment: 'production',
    allocation: 3000,
    used: 910,
    remaining: 2090,
    cap: 3000,
    status: 'paused',
    alertThresholds: {
      enabled: true,
      thresholds: [80, 100],
      recipients: ['admin@example.com'],
    },
    lastAlertedThreshold: null,
    createdAt: '2026-02-15',
    updatedAt: '2026-03-10',
  },
];
