import type { Entitlement } from '../../types/portalTypes';

export const MOCK_ENTITLEMENTS: Entitlement[] = [
  {
    id: 'ent-1',
    productSlug: 'esims',
    productName: 'eSIMs',
    productIcon: 'Smartphone',
    description: 'International mobile connectivity',
    environment: 'test',
    allocation: 1000,
    used: 347,
    remaining: 653,
    cap: 1000,
    status: 'active',
    alertThresholds: {
      enabled: true,
      thresholds: [50, 80, 90, 100],
      recipients: ['admin@example.com'],
    },
    lastAlertedThreshold: null,
    createdAt: '2026-01-15',
    updatedAt: '2026-03-17',
  },
  {
    id: 'ent-2',
    productSlug: 'airport-lounge',
    productName: 'Airport Lounge',
    productIcon: 'Sofa',
    description: 'Premium airport lounge access',
    environment: 'test',
    allocation: 20000,
    used: 17450,
    remaining: 2550,
    cap: 20000,
    status: 'active',
    alertThresholds: {
      enabled: true,
      thresholds: [50, 80, 90, 100],
      recipients: ['admin@example.com'],
    },
    lastAlertedThreshold: 80,
    createdAt: '2026-01-15',
    updatedAt: '2026-03-17',
  },
  {
    id: 'ent-3',
    productSlug: 'airport-transfer',
    productName: 'Airport Transfer',
    productIcon: 'Car',
    description: 'Ground transportation services',
    environment: 'production',
    allocation: 5000,
    used: 1230,
    remaining: 3770,
    cap: 5000,
    status: 'active',
    alertThresholds: {
      enabled: true,
      thresholds: [50, 80, 90, 100],
      recipients: ['admin@example.com'],
    },
    lastAlertedThreshold: null,
    createdAt: '2026-01-15',
    updatedAt: '2026-03-17',
  },
];
