import { useState } from 'react';
import { Info, X } from 'lucide-react';
import { SectionHeading } from '../../shared/SectionHeading';
import { useEnvironment } from '../../../contexts/EnvironmentContext';
import { ApiKeysTable } from './ApiKeysTable';
import { MOCK_API_KEYS } from './mockApiKeys';

export function ApiKeysSection() {
  const { environment } = useEnvironment();
  const [keys] = useState(MOCK_API_KEYS);
  const [showBanner, setShowBanner] = useState(() => {
    return sessionStorage.getItem('dp_keys_banner_shown') !== 'true';
  });

  const filteredKeys = keys.filter(k => k.environment === environment);

  const dismissBanner = () => {
    setShowBanner(false);
    sessionStorage.setItem('dp_keys_banner_shown', 'true');
  };

  return (
    <div>
      <SectionHeading>API Keys</SectionHeading>
      <p className="font-['Cabin',sans-serif] text-[13px] text-[#6a7282] mb-4">
        Your API keys for the <span className="font-semibold capitalize">{environment}</span> environment. Keys are generated by Dragonpass during onboarding — contact your account manager to request additional keys.
      </p>

      {showBanner && environment === 'test' && (
        <div className="bg-[#eff6ff] border border-[#93c5fd] rounded-lg p-3 mb-4 flex items-start justify-between">
          <div className="flex items-start gap-2">
            <Info size={14} className="text-[#2563eb] mt-0.5 shrink-0" />
            <p className="font-['Cabin',sans-serif] text-[13px] text-[#1e40af]">
              These are your test credentials. Use them to integrate and test the Dragonpass API. When you're ready for production, request access below.
            </p>
          </div>
          <button onClick={dismissBanner} className="cursor-pointer shrink-0 ml-2">
            <X size={14} className="text-[#2563eb]" />
          </button>
        </div>
      )}

      <ApiKeysTable keys={filteredKeys} />
    </div>
  );
}
